name: Test

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
          path: develop
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Install & build
        working-directory: ./develop
        run: |
          npm install
          npm run build
      - name: Clear master content
        run: find . -not -path "/master/.git/*" -delete
      - name: Build site assets
        run: ls -la
      - name: Move build content in develop to master
        run: mv develop/build master
      - name: Push changes to deploy
        working-directory: master
        run: |
          if ! git diff --no-ext-diff --quiet --exit-code; then
            git add .
            git config user.email "johnwongwwc@gmail.com"
            git config user.name "WaiChungWong"
            git commit -m "Deployment at ${{ steps.date.outputs.date }}"
            git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master
          fi
