name: Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use git commands
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - run: git stash
      - run: git checkout master
      - run: git stash pop
      - run: git add .
      - run: git -c --local user.email "action@github.com" -c --local user.name "GitHub Action" commit -m "Update website"
      - run: git push -q "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master
