name: Test

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
          path: develop
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Install & build
        working-directory: develop
        run: |
          npm install
          npm run build
      - name: Clear content in master branch
        working-directory: master
        run: rm -rf 'ls .'
      - name: Move build content in develop to master
        run: mv develop/build/* master
      - name: Push changes to deploy
        working-directory: master
        run: |
            git add .
            git config user.email "johnwongwwc@gmail.com"
            git config user.name "WaiChungWong"
            git commit -m "Deployment at ${{ steps.date.outputs.date }}"
            git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master
