name: Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Install & build
        run: |
          npm install
          npm run build
      - name: Upload build as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Download build from artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
          path: .
      - name: Push changes to deploy
        run: |
          if ! git diff --no-ext-diff --quiet --exit-code; then
            git add .
            git status
            git config user.email "johnwongwwc@gmail.com"
            git config user.name "WaiChungWong"
            git commit -m "Deploy website"
            git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master
          fi
