name: Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - run: npm install
      - run: npm run build
      - run: git add build
      - run: git status
      - run: git config user.email "action@github.com"
      - run: git config user.name "GitHub Action"
      # - run: git commit -m "commit build"
      # - run: git push -q "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" develop
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Checkout develop's build folder
        uses: actions/checkout@v2
        with:
          ref: develop build
          path: build
      # - run: rsync -r build/* .
      # - run: rm -rf build
      - run: git add .
      - run: git status
      - run: git commit -m "Update website"
      - run: git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master
