name: Test

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: WaiChungWong/github-action-test-2@v1
        with:
          node-version: 12.x
          gh-pages-branch: master
          build-branch: develop
          build-script: |
            npm install
            npm run build
          build-path: build
          commit-author: GitHub Action
          commit-email: github-actions@github.com
      
