name: Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - run: npm install
      - run: npm run build
      - run: git stash
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
