name: Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - run: npm install
      - run: npm run build
      - name: Upload build as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Download build from artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
          path: .
      - run: git add .
      - run: git status
      - run: git config user.email "action@github.com"
      - run: git config user.name "GitHub Action"
      - run: git commit -m "Deploy website"
      - run: git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master
